version: "3.8"
services:
  qaproject:
    container_name: qaproject
    image: omar99g/qaproject:latest
    build: .
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@qaproject_database:3306/project
      CREATE_SCHEMA: 
    depends_on:
    - database
  database:
    container_name: qaproject_database
    image: mysql:5.7
    ports:
    - target: 80
      published: 80
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
    volumes:
    - type: volume
      source: qaproject_database_volume
      target: /var/lib/mysql
volumes:
  qaproject_database_volume: